spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
    - name: 'adblock-nocoin-list'
    path: 'https://cdn.jsdelivr.net/gh/hoshsadiq/adblock-nocoin-list/hosts.txt'
    
    - name: 'Scam Blocklist'
    path: 'https://cdn.jsdelivr.net/gh/durablenapkin/scamblocklist/adguard.txt'
    
    - name: 'Dan Pollock's List'
    path: 'https://someonewhocares.org/hosts/zero/hosts'
    
    - name: 'AdGuard DNS filter'
    path: 'https://cdn.jsdelivr.net/gh/AdguardTeam/FiltersRegistry/filters/filter_15_DnsFilter/filter.txt'
    
    - name: 'Peter Lowe's List'
    path: 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext'
    
    - name: 'OISD Blocklist Basic'
    path: 'https://abp.oisd.nl/basic/'
    
    - name: 'WindowsSpyBlocker'
    path: 'https://cdn.jsdelivr.net/gh/crazy-max/WindowsSpyBlocker/data/hosts/spy.txt'
    
    - name: 'yhosts'
    path: 'https://cdn.jsdelivr.net/gh/VeleSila/yhosts/hosts.txt'
    
    - name: '大圣净化'
    path: 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts'
    
    - name: 'AdRules AdGuard Full List'
    path: 'https://code.gitlink.org.cn/hacamer/AdRules/raw/branch/main/adguard-full.txt'
    
    - name: 'adguard base'
    path: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt'
    
    - name: 'anti-AD'
    path: 'https://anti-ad.net/easylist.txt'
    
    - name: 'AdGuard CNAME 伪装跟踪器列表'
    path: 'https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers.txt'

    #本地规则文件
    local:
      - name: 'local rule'
        path: 'local-rule.txt' #支持绝对/相对路径

  #输出配置
  output:
    #生成的规则文件头部内容, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
    file_header: |
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/fordes123/ad-filters-subscriber/

    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进）
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则
        - MODIFY  #修饰规则，添加了一些修饰符号的规则
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
