spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
    - name: 'adblock-nocoin-list'
  path: 'https://cdn.jsdelivr.net/gh/hoshsadiq/adblock-nocoin-list/hosts.txt'
- name: 'Scam Blocklist'
  path: 'https://cdn.jsdelivr.net/gh/durablenapkin/scamblocklist/adguard.txt'
- name: 'Dan Pollock's List'
  path: 'https://someonewhocares.org/hosts/zero/hosts'
- name: 'AdGuard DNS filter'
  path: 'https://cdn.jsdelivr.net/gh/AdguardTeam/FiltersRegistry/filters/filter_15_DnsFilter/filter.txt'
- name: 'Peter Lowe's List'
  path: 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext'
- name: 'OISD Blocklist Basic'
  path: 'https://abp.oisd.nl/basic/'
- name: 'WindowsSpyBlocker'
  path: 'https://cdn.jsdelivr.net/gh/crazy-max/WindowsSpyBlocker/data/hosts/spy.txt'
- name: 'yhosts'
  path: 'https://cdn.jsdelivr.net/gh/VeleSila/yhosts/hosts.txt'
- name: '大圣净化'
  path: 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts'
- name: 'AdRules AdGuard Full List'
  path: 'https://code.gitlink.org.cn/hacamer/AdRules/raw/branch/main/adguard-full.txt'
- name: 'adguard base'
  path: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt'
- name: 'anti-AD'
  path: 'https://anti-ad.net/easylist.txt'
- name: 'AdGuard CNAME 伪装跟踪器列表'
  path: 'https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers.txt'
- name: 'AdGuard DNS filter'
  path: 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt'
- name: 'AdditionalFiltersCN'
  path: 'https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt'
- name: 'ADgk 移动广告规则'
  path: 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt'
- name: '乘风 广告过滤规则'
  path: 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt'
- name: '乘风 视频过滤规则'
  path: 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt'
- name: 'HalfLife_合并自乘风视频广告过滤规则、EasylistChina、EasylistLite、CJX'sAnnoyance'
  path: 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt'
- name: 'AdAway 官方的去广告 Host 规则'
  path: 'https://adaway.org/hosts.txt'
- name: '去除禁止广告拦截提示规则'
  path: 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt'
- name: 'Yhosts规则'
  path: 'https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt'
- name: '大圣净化（针对国内视频）'
  path: 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts'
- name: '杏稍AdRules DNS List'
  path: 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt'
- name: 'AdGuard_blackmatrix7合并'
  path: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/AdGuard/Advertising/Advertising.txt'
- name: '知乎 普通版'
  path: 'https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu.txt'
- name: '217heidai/adblockfilters去重合并(比较大)'
  path: 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt'
- name: 'Youtube-Adfilter-Web'
  path: 'https://raw.githubusercontents.com/timlu85/AdGuard-Home_Youtube-Adfilter/master/Youtube-Adfilter-Web.txt'
- name: 'ublock-filters-ulist-youtube'
  path: 'https://raw.githubusercontents.com/91ajames/ublock-filters-ulist-youtube/main/blocklist.txt'
- name: '秋风广告规则,针对Android广告'
  path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt'
- name: '每日规则'
  path: 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/daily.txt'
- name: 'AdGuard规则'
  path: 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/adg.txt'
- name: 'Banben规则'
  path: 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/adgk.txt'
- name: 'Yhosts规则'
  path: 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/yhosts.txt'
- name: 'StevenBlack规则'
  path: 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/steven.txt'
- name: 'uBlock filters'
  path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/filters.txt'
- name: 'uBlock filters – Badware risks'
  path: 'https://ublockorigin.pages.dev/filters/badware.txt'
- name: 'uBlock filters – Privacy'
  path: 'https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/filters/privacy.txt'
- name: 'uBlock filters – Quick fixes'
  path: 'https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt'
- name: 'uBlock filters – Resource abuse'
  path: 'https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/resource-abuse.txt'
- name: 'uBlock filters – Unbreak'
  path: 'https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/filters/unbreak.txt'
- name: 'AdGuard Mobile Ads移动设备'
  path: 'https://filters.adtidy.org/extension/ublock/filters/11.txt'
- name: 'EasyList'
  path: 'https://easylist-downloads.adblockplus.org/easylist.txt'
- name: 'EasyList China'
  path: 'https://easylist-downloads.adblockplus.org/easylistchina.txt'
- name: 'EasyPrivacy'
  path: 'https://easylist-downloads.adblockplus.org/easyprivacy.txt'
- name: 'EasyList Cookie List'
  path: 'https://easylist-downloads.adblockplus.org/easylist-cookie.txt'
- name: 'Anti-AD'
  path: 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt'
    #本地规则文件
    local:
      - name: 'local rule'
        path: 'local-rule.txt' #支持绝对/相对路径

  #输出配置
  output:
    #生成的规则文件头部内容, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
    file_header: |
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/fordes123/ad-filters-subscriber/

    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进）
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则
        - MODIFY  #修饰规则，添加了一些修饰符号的规则
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
